### ISSUE TITLE
Un schéma PAGE ?

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/HTRVX#1]
Est-ce qu'on peut envisager de créer un schéma pour la validation de dépôts d'XML PAGE?

**Comment by PonteIneptique** [comment]
Il faudrait mais j'attends la mise à jour de l'ontologie :D

Le jeu. 25 nov. 2021 à 5:16 PM, Alix Chagué ***@***.***> a
écrit :

**Comment by PonteIneptique** [comment]
Done !
