### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by sven-nm** [HTR-United/HTRVX#10]
Hi team, I make successful usage of HTRVX, thanks for that ! Here are just two tiny things I would suggest : 

- I would change `ALTO` to `alto` in the table from the readme, as the caps are misleading. 
- Adding a purely pythonic API would be amazing, as it would allow to validate xmls before exporting them. Especially so that `ET.tree`s can already be passed as file in `testing.apply_tests()` ; adding a parser from strings (e.g. coming from Jinja2 templates) would also be cool. Something like 
```Python
from htrvx.testing import apply_tests
apply_tests(your_xml: Union[file,str,ET.tree], **{your_params})
```

Anyways, just ideas, thanks for the good job !

**Comment by PonteIneptique** [comment]
Hey :)
I thought I replied to this issue but yes, I agree :) I'll take care of that in the coming weeks ;)

**Comment by PonteIneptique** [comment]
Hey @sven-nm,
Would the work done in #14 be good for you ? I assume everything is stored as it is, you might want to change print to something else but otherwise... It seems OK on my end.
