### ISSUE TITLE
`GraphicZone` missing?

### ISSUE THREAD

**Issue by gabays** [HTR-United/HTRVX#7]
https://github.com/HTR-United/HTRVX/blob/c937b458e3ad27f50ec2ea5c77435560332a1562/htrvx/zones.py#L6

It seems that there is a zone missing: [GraphicZone](https://github.com/SegmOnto/Guidelines/tree/main/zones/GraphicZone) no?

**Comment by PonteIneptique** [comment]
I'd say the issue is more that decoration zone has been renamed :) feel
free to pr

Le dim. 6 mars 2022 à 3:40 PM, Simon Gabay ***@***.***> a
écrit :

**Comment by gabays** [comment]
True dat

**Comment by PonteIneptique** [comment]
You should also probably rename the md file on segmonto

Le dim. 6 mars 2022 à 3:47 PM, Simon Gabay ***@***.***> a
écrit :

**Comment by gabays** [comment]
True dat too

**Comment by gabays** [comment]
PR is done actually. https://github.com/SegmOnto/Guidelines/pull/49
@Jean-Baptiste-Camps can you validate the PR?

**Comment by gabays** [comment]
Should be done by JB. We close the issue?

**Comment by PonteIneptique** [comment]
0.0.9 released
